ARG ARCH
ARG VERSION
ARG VARIANT

FROM docker.cloudsmith.io/iniationware-gmbh/app-stores/p4nr/node-red-opcua-flecs:${VERSION}

ARG ARCH
ARG VERSION
ARG VARIANT

RUN [ ! -z "${ARCH}" ]
RUN [ ! -z "${VERSION}" ]
